name: my_flutter
description: A new flutter module project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  cookie_jar: ^1.0.0
  crypto: 2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.myflutter
    iosBundleIdentifier: com.example.myFlutter
